import { TYPE_ABSOLUTE_UNIT } from "./ABSOLUTE_UNIT";

export default {
  i: "space",
  x: 0,
  y: 0,
  w: 100,
  h: 100,
  z: 0,
  m: [
    {
      i: "space",
      x: 0,
      y: 0,
      w: 50,
      h: 50,
      z: 1,
      m: [
        {
          i: "space",
          x: 0,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 0,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
      ],
    },
    {
      i: "space",
      x: 50,
      y: 0,
      w: 50,
      h: 50,
      z: 1,
      m: [
        {
          i: "space",
          x: 0,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 0,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
      ],
    },
    {
      i: "space",
      x: 0,
      y: 50,
      w: 50,
      h: 50,
      z: 1,
      m: [
        {
          i: "space",
          x: 0,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 0,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
      ],
    },
    {
      i: "space",
      x: 50,
      y: 50,
      w: 50,
      h: 50,
      z: 1,
      m: [
        {
          i: "space",
          x: 0,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 0,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 0,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
        {
          i: "space",
          x: 50,
          y: 50,
          w: 50,
          h: 50,
          z: 2,
        },
      ],
    },
  ],
} as TYPE_ABSOLUTE_UNIT;
